export const categoriesInfo = {
  categories: [
    {
      id: 2,
      name: "Печи для бани",
      brands: [
        "Везувий",
        "ASTON",
        "ЭТНА",
        "Эверест",
        "Сталь-Мастер",
        "Термофор (Конвектика)",
        "Варвара",
        "BORN",
        "ВВД",
        "Теплодар",
        "Ермак",
        "КДМ",
        "Grill'D",
        "Везувий",
        "ASTON",
        "ЭТНА",
        "Эверест",
        "Сталь-Мастер",
        "Термофор (Конвектика)",
        "Варвара",
        "BORN",
        "ВВД",
        "Теплодар",
        "Ермак",
        "КДМ",
        "Grill'D",
      ],
      features: [
        "Везувий",
        "ASTON",
        "ЭТНА",
        "Эверест",
        "Сталь-Мастер",
        "Термофор (Конвектика)",
        "Варвара",
        "BORN",
        "ВВД",
        "Теплодар",
        "Ермак",
        "КДМ",
        "Grill'D",
      ],
      accessories: [
        "Везувий",
        "ASTON",
        "ЭТНА",
        "Эверест",
        "Сталь-Мастер",
        "Термофор (Конвектика)",
        "Варвара",
        "BORN",
        "ВВД",
        "Теплодар",
        "Ермак",
        "КДМ",
        "Grill'D",
      ],
    },
    {
      id: 3,
      name: "Печи для дома",
      brands: [
        "Термофор (Конвектика)",
        "greo G",
        "Везувий",
        "Guca",
        "Рубцовск",
        "MBS",
        "greo R",
        "Kratki",
        "Firebird",
        "ASTON",
        "Мета-Бел",
        "ABX",
        "Бавария",
        "ЭТНА",
        "Каминити",
        "МЕТА",
        "НМК",
        "LK",
        "Эверест",
        "КДМ",
        "Теплодар",
        "Ермак",
        "Варвара",
      ],
      features: [],
      accessories: [],
    },
    {
      id: 4,
      name: "Камины",
      brands: [],
      features: [],
      accessories: [],
    },
    {
      id: 11,
      name: "Котлы",
      brands: [],
      features: [],
      accessories: [],
    },
    {
      id: 5,
      name: "Дымоходы",
      brands: [],
      features: [],
      accessories: [],
    },
    {
      id: 6,
      name: "Печное литье",
      brands: [],
      features: [],
      accessories: [],
    },
    {
      id: 7,
      name: "Барбекю зона",
      brands: [],
      features: [],
      accessories: [],
    },
    {
      id: 8,
      name: "Товары для печника",
      brands: [],
      features: [],
      accessories: [],
    },
    {
      id: 9,
      name: "Товары для бани",
      brands: [],
      features: [],
      accessories: [],
    },
    {
      id: 10,
      name: "Аксессуары",
      brands: [],
      features: [],
      accessories: [],
    },
  ],
};
